name: cop_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 
  image_picker: ^0.8.4+4  
  geolocator: ^7.0.3 
  permission_handler: ^10.3.0 
  url_launcher: ^6.1.11 
  flutter_email_sender: ^5.0.1
  mailer: ^6.1.0 
  flutter_dotenv: ^5.1.0
  sqflite: any
  path_provider: ^2.1.3
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.6
  flutter_form_builder: ^7.5.0
  pdf: ^3.7.0
  printing: ^5.9.1
  flutter_phone_direct_caller: ^2.1.0
  path: any
  

flutter_icons:
  android: true
  ios: true
  image_path: "asserts/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - asserts/
